env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
ignorePatterns:
  - "build/*"
  - "static/js/*.js"
rules:
  react/prop-types: "off"
settings:
  react:
    version: "detect"
